version: "2.6.0"

services:
  api:
   build:
     context: .
     dockerfile: ./infrastructure/Dockerfile
   restart: always
   container_name: lib-serv
   volumes:
     - ./.env:/app/.env
   network_mode: bridge
   
  nginx:
    image: nginx:latest
    restart: always
    volumes:
    - ./infrastructure/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: bridge
    ports:
      - "80:80"
  pg-database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "12345"
    volumes:
      #- ../2. Init Database:/docker-entrypoint-initdb.d
      - /var/lib/docker/volumes/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
 