version: "2.6.0"

services:
  api:
   build:
     context: .
     dockerfile: ./infrastructure/Dockerfile
   restart: always
   container_name: lib-serv
   volumes:
     - ./.env:/app/.env
  nginx:
    image: nginx:latest
    restart: always
    volumes:
    - ./infrastructure/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
   

  

  
 