version: "2.6.0"

services:
  api:
   build:
     context: .
     dockerfile: ./infrastructure/Dockerfile
   restart: always
   container_name: lib-serv
   volumes:
     - ./.env:/app/.env
   network_mode: bridge
   
  nginx:
    image: nginx:latest
    restart: always
    volumes:
    - ./infrastructure/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: bridge
    ports:
      - "80:80"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD 12345
    volumes:
      #- ./migrations:/docker-entrypoint-initdb.d
      - test_db:var/lib/postgresql/data
    network_mode: bridge
    ports:
      - "5432:5432"
  
 