version: "2.6.0"

services:
  api:
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    restart: always
    depends_on:
      - pg-database
    container_name: lib-serv
    network_mode: bridge
  
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./infrastructure/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    network_mode: bridge
  
  pg-database:
    image: postgres:latest
    depends_on:
      - nginx
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./migrations/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./.database/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: bridge
